### PR TITLE
Rebase BeaconBlockBodyMerge on top of BeaconBlockBodyAltair

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

- Extract `BeaconBlockBody*` and `BeaconBlockBodySchema*` interfaces to make possible `Phase0 -> Altair -> Merge -> ...` structures inheritance
- Rebase `BeaconBlockBodyMerge` on top of `BeaconBlockBodyAltair`

Part of implementation for #4351

### CODE REVIEW

**Comment by Nashatyrev** [comment]
Hm... Now I'm not so sure if that inheritance actually makes sense. Some field might be removed at some fork and inheritance couldn't be applied. Like for `phase0 -> Altair` `BeaconState` versions 
I also see that other structures don't inherit from `phase0` to `altair`.

**Comment by Nashatyrev** [comment]
From the other side making `BeaconStateMerge` without inheriting `BeaconStateAltair` would require a lot of Altair logic to be copy-and-pasted from `altair` to `merge` version. So I'm currently sticking to inherit where possible. Not an ideal solution but for now seems to be better than copy-pasting.

**Review by ajsutton — APPROVED** [review]
This is great work, though I really don't like the complexity of type hierarchy, interfaces and schemas we've wound up with.  I'm not seeing a lot of better options though so I think this is the way to move forward at least for interop.  I think for block body the right approach may be to just have on `BeaconBlockBody` interface and it exposes `Optional<SyncAggregate> getSyncAggregate()` type methods.  So instead of `toVersionAltair` returning the optional it's `getSyncAggregate()` that does.  That's a pretty significant change that goes beyond the merge work though so let's stick with this for now and we'll experiment with alternatives when we start merging this master.

**Comment by ajsutton** [comment]
Merging this into the `merge-interop` branch via: https://github.com/ConsenSys/teku/pull/4352

**Comment by Nashatyrev** [comment]
Closing this to continue on branch https://github.com/ConsenSys/teku/tree/merge-interop

**Pull request closed without merging**
